name: 'Mirror private repo changes in the dual public repo'
description: 'Used to duplicate a single repo between an internal (private)
              instance and a public facing instance.'
inputs:
  github_secret_pat:
    description: 'The GitHub Personal Access Token (PAT) with necessary
                  permissions to publish a commit in the public repository'
    required: true
  user_name:
    description: 'GitHub username for the commit.

                  Default: <github.actor>'
    required: false
    default: '${{ github.actor }}'
  user_email:
    description: 'Email for the git commit.

                  Default: <github.actor>@users.noreply.github.com'
    required: false
    default: '${{ github.actor }}@users.noreply.github.com'
  public_gitignore_filename_convention:
    description: 'The conventioned used to name your files that store the list
                  of files that should be in the .gitignore of the public repo,
                  but which you want to track in your private repo. (i.e., they
                  themselves are not .gitignore files, but will be aggregated to
                  create one only for the public commits).

                  Default: "public.gitignore"'
    required: false
    default: 'public.gitignore'
  private_subdir:
    description: 'The directory (relative to "GITHUB_WORKSPACE") where the
                  private repo lives within the GH Actions runner.

                  Default: "private"'
    required: false
    default: 'private'
  public_repo:
    description: 'The full name of the repo that is used as the public facing
                  instance of the pair.

                  Default: The name of the private repo, with a presumed
                           "_private" truncated from the end.'
    required: false
  working_branch_name:
    description: 'The name of the target branch in the public repo.

                  TODO: Resolve following possabilities
                    - Target branch does NOT exist
                    - Target branch DOES exist
                    -- Target branch is a simple BRANCH
                    --- Target PR IS owned by source PR author
                    --- Target PR is NOT owned by source PR author
                    -- Target branch is a PULL REQUEST
                    --- Target branch IS owned by source PR author
                    --- Target branch is NOT owned by source PR author

                  Default: <github.head_ref>'
    required: false
    default: ${{ github.head_ref }}
  commit_message:
    description: 'A custom message for the commit.

                  Default: <github.event.head_commit.message>'
    required: false
    default: ${{ github.event.head_commit.message }}
  git_server:
    description: 'Git server host.

                  Default: github.com'
    required: false
    default: 'github.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-secret-pat }}
    - ${{ inputs.user-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.public-gitignore-filename-convention }}
    - ${{ inputs.private-dir }}
    - ${{ inputs.public-dir }}
    - ${{ inputs.working-branch-name }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.git-server }}
branding:
  icon: 'git-commit'
  color: 'green'
